Week_02
AndreLinhares-Dev/wdd130 pull request #6
Opened 2024-09-27 08:28 UTC by AndreLinhares-Dev

2024-09-30 07:16 UTC, bos21001 commented on styles/styles.css
> +    border: 1px solid rgba (0,0,0, 0.2);
### Error Message
[CSS Validation Service](https://jigsaw.w3.org/css-validator/validator?uri=AndreLinhares-Dev.github.io/wdd130/)
![image](https://github.com/user-attachments/assets/4039b55c-f1a5-4a3b-99f9-3f3a518e406b)

### Solution
The CSS Validation Service is returning an error in your CSS. To resolve this, you simply need to remove the space between the `rgb` function and its parameters. It should look like this: `rgb(0, 0, 0, 0.2);`

2024-09-30 07:22 UTC, bos21001 commented on week02/excersise2/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
### Error Message
![image](https://github.com/user-attachments/assets/0ed7a39f-2f69-46cf-9c97-c4127c047078)

### Solution
Add a meta description in the `<head>` tag, like this: `<meta name="description" content="[the description here]">`.

2024-09-30 07:38 UTC, bos21001 commented on styles/styles.css
> +}
### Error Message
![image](https://github.com/user-attachments/assets/8581c54a-8877-41ec-9260-d0112a0637ed)

### Solution
Refer back to the course content to resolve this issue: [Course Content](https://byui-cse.github.io/wdd130-ww-course/week02/prove-home-enhancement-css.html#:~:text=Set%20the%20img%20inside%20the%20aside%20to%20have%20a%20width%20of%20200%20pixels%20and%20a%20height%20of%20auto).

2024-09-30 07:40 UTC, bos21001 commented on styles/styles.css
> +}
### Error Message
![image](https://github.com/user-attachments/assets/14be32b6-e459-4f4e-b8af-560c7ec5dae7)

### Solution
Refer back to the course content to resolve this issue: [Course Content](https://byui-cse.github.io/wdd130-ww-course/week02/prove-home-enhancement-css.html#:~:text=Set%20the%20img%20inside%20the%20aside%20to%20have%20a%20width%20of%20200%20pixels%20and%20a%20height%20of%20auto).

2024-09-30 07:44 UTC, bos21001 commented on styles/styles.css
> +}
### Error Message
![image](https://github.com/user-attachments/assets/56d6a3f1-5301-41d6-8c17-9f532518605f)

### Solution
Refer back to the course content to resolve this issue: [Course Content](https://byui-cse.github.io/wdd130-ww-course/week02/prove-home-enhancement-css.html#:~:text=Apply%20CSS%20to%20the%20%3Cfooter%3E%20element%20to%201%EF%B8%8F%E2%83%A3add%20a%20top%20margin%20to%20separate%20it%20from%20the%20main%20element%20content%2C%202%EF%B8%8F%E2%83%A3add%20a%20top%20border%20to%20design%20additional%20distinction%20from%20the%20main%20content%2C%20and%203%EF%B8%8F%E2%83%A3align%20the%20any%20text%20in%20the%20footer%20to%20the%20center%20of%20its%20content%20box.).

2024-09-30 08:12 UTC, bos21001 requested changes
Hey Andre, could you please review the comments I added to your pull request and address them as soon as possible?

2024-09-30 08:15 UTC, bos21001 commented on index.html
> +    <link rel="stylesheet" href="styles/styles.css">
### Error Message
![image](https://github.com/user-attachments/assets/0ed7a39f-2f69-46cf-9c97-c4127c047078)

### Solution
Add a meta description in the `<head>` tag, like this: `<meta name="description" content="[the description here]">`.

2024-10-02 09:05 UTC, chrsmendes approved these changes
Great job!!

2024-10-02 09:05 UTC, merged

2024-10-02 09:05 UTC, bos21001 commented
Well done!